---
title: "How to make your deep learning model available"
format: html
---

The idea behind the deep learning module in PAMGuard is to make published deep learning classifiers available to the wider community. Researchers get access to cutting edge classifiers and authors get more exposure, citations and in general make a greater impact after their hard work - win win!

If you want to make your model available there are a few things you will need to do.

1.  Firstly, you will need a deep learning model that works in PAMGuard - see \[here\]() for more information on how to do that.

2.  Create a settings file which shows an example of the deep learning model running.

3.  Create a Markdown document which provides an overview of your model. Use the Shiu/Palmer Right whale model as a template. Note this **must** include a link to a publication which describes your model in detail.

4.  Archive the model, settings file and example sound file in a public repository such as Zenodo so that it has a DOI.

Once that is all done, send us through everything - we will check it over and if all OK publish on the website.
