---
title: "Garrobe et al. 2024"
description: "New publication comparing existing PAMGuard detectors with new machine learning methods"
date: 2024-12-18
---
[https://doi.org/10.1121/10.0034602](https://doi.org/10.1121/10.0034602)
 
Comparing neural networks against click train detectors
to reveal temporal trends in passive acoustic sperm whale
detections

Laia Garrobe Fonollosa, Thomas Webber, Jose Maria Brotons, Margalida Cerda,
Douglas Gillespie, Enrico Pirotta, and Luke Rendell

ABSTRACT

Passive acoustic monitoring (PAM) is an increasingly popular tool to study vocalising species. The amount of data generated by PAM studies calls for robust automatic classifiers. Deep learning (DL) techniques have been proven effective in identifying acoustic signals in challenging datasets, but due to their black-box nature their underlying biases are hard to quantify. This study compares human analyst annotations, a multi-hypothesis tracking (MHT) click train classifier and a DL-based acoustic classifier to classify acoustic recordings based on the presence or absence of sperm whale (Physeter macrocephalus) click trains and study the temporal and spatial distributions of the Mediterranean sperm whale subpopulation around the Balearic Islands. The MHT and DL classifiers showed agreements with human labels of 85.7% and 85.0%, respectively, on data from sites they were trained on, but both saw a drop in performance when deployed on a new site. Agreement rates between classifiers surpassed those between human experts. Modeled seasonal and diel variations in sperm whale detections for both classifiers showed compatible results, revealing an increase in occurrence and diurnal activity during the summer and autumn months. This study highlights the strengths and limitations of two automatic classification algorithms to extract biologically useful information from large acoustic datasets. VC 2024 Acoustical Society of America.
