---
title: "Version 2.02.18"
description: "PAMGuard version 2.02.18 is now available for Windows, Mac, and Linux"
date: 2026-02-20
---

[PAMGuard version 2.02.18](../downloadsurvey.qmd) is now available for Windows, Mac, and Linux.

## PAMGuard 2.02.18 is now available

Version [2.02.18](../downloadsurvey.qmd) includes a number of minor new features and bug fixes. 

We've started to distribute an installer for Debian-based Linux systems - we are trialling to see how this goes. Linux is still a very fragmented ecosystem, and we can't guarantee that the installer will work on all Debian-based Linux distributions (it won't work on Fedora, etc.), but we hope it will make installation easier for some users. There are also some instructions [here](https://github.com/PAMGuard/PAMGuard/blob/main/build/COMPILE.md) on how to manually build PAMGuard on Linux. 

We also implemented Apple's new security features, so the macOS installer should now only warn users once that PAMGuard was downloaded from the Internet, and the app should be able to access the computer's microphone (subject to user permission) without any workarounds. Get in touch if this does not work.

::: callout-note
We know it's frustrating if PAMGuard does not work, and (subject to [funding](../funding.qmd)) we are taking steps to make releases more stable by developing a new test framework. It's going to take time, and we won't catch every bug, but it should mean that in the coming few years PAMGuard is generally more resilient to bugs, making life easier for developers and users!
:::

Here's a full list of what was done and you can always check out [GitHub Issues page](https://github.com/PAMGuard/PAMGuard/issues) to see what specifically was fixed.

## New Features

Options in internal storage management to NOT delete all data from memory each time PAMGuard starts. [See online help](https://www.pamguard.org/olhelp/overview/PamMasterHelp/docs/internalstorage.html). This can be used to stop the map from clearing whenever the acquisition resets for unknown reasons. Also updated help for internal storage options.

New module to compute a [Mel spectrogram](https://www.pamguard.org/olhelp/sound_processing/mel/docs/mel_overview.html)

FFT Filter option in [Filters Module](https://www.pamguard.org/olhelp/sound_processing/FiltersHelp/Docs/Filters_filters.html)

[Binary Store](https://www.pamguard.org/olhelp/utilities/BinaryStore/docs/binarystore_overview.html) option to update all binary files to the latest version. This can be useful if you want to open old binary files with the latest versions of the [Matlab, R, and Python libraries](https://www.pamguard.org/matlabandr.html).

Tethys output for One band Filtered noise measurements

Support for DeepAcoustics AI models

SoundTrap wav files now have millis time and PAMGuard starts at the start time of each file, not the sample clock

DMG on macOS can now access computer's microphone but mac security requires user to accept a prompt

## Bug Fixes / minor enhancements

[Issue 292](https://github.com/PAMGuard/PAMGuard/issues/292): Export of click events was not including all clicks within each event. Now resolved.

[Issue 286](https://github.com/PAMGuard/PAMGuard/issues/286): Soundtrap SUD time. Issue fixed, though you should generally NEVER set a time zone offset for SUD files. See [online help](https://www.pamguard.org/olhelp/detectors/clickDetectorHelp/docs/SoundTrapClickDetector.html).

[Issue 285](https://github.com/PAMGuard/PAMGuard/issues/285): Fixed bugs in DelphinID, which was not working.

[Issue 280](https://github.com/PAMGuard/PAMGuard/issues/280): Fix long standing bug in click detector BT display where last click was not showing

[Issue 238](https://github.com/PAMGuard/PAMGuard/pull/283): Updates SUD file reader to correctly zero-pad files with missing chunks.

[Issue 279](https://github.com/PAMGuard/PAMGuard/issues/279): Problems with user specified date formats. Improved help file and issue warning if a 12 hour time format is specified.

[Issue 273](https://github.com/PAMGuard/PAMGuard/issues/273): Fixed (or improved) night mode display for logger forms.

[Issue 272](https://github.com/PAMGuard/PAMGuard/issues/272): Bearing localiser was truncating the clicks if set to only measure bearings using first n samples.

[Issue 270](https://github.com/PAMGuard/PAMGuard/issues/270): Added options on click BT display pop up menu to manually classify groups of marked clicks as well as single clicks.

[Issue 266](https://github.com/PAMGuard/PAMGuard/issues/266): Tethys failing to export Deployment documents when missing sound recording data. Now fixed.

[Issue 265](https://github.com/PAMGuard/PAMGuard/issues/265): Clock setting from GPS. This has not worked for a number of years due to Windows security settings. A work around has now been found and documented in the help files.

[Issue 261](https://github.com/PAMGuard/PAMGuard/pull/261): Restore choseable symbols for swing spectrogram displays of DL detection data

[Issue 260](https://github.com/PAMGuard/PAMGuard/issues/260): Issue popup warning in sound acquisition when no sound files are present.

[Issue 258](https://github.com/PAMGuard/PAMGuard/issues/258): Improved error reporting from database and binary store modules

[Issue 255](https://github.com/PAMGuard/PAMGuard/issues/255): Fixed bug causing occasional crash in click spectrum display.

[Issue 254](https://github.com/PAMGuard/PAMGuard/issues/254): AIS Error. Fix bug occurring when AIS data arrive before first GPS Position

[Issue 251](https://github.com/PAMGuard/PAMGuard/issues/251): ROCCA: Fixed bug that caused contour tracking to crash if the contour was close to 0Hz or close to the Nyquist frequency.

[Issue 250](https://github.com/PAMGuard/PAMGuard/issues/250): Ishmael energy sum and spectrogram correlation detectors not using correct min gap between detections. Now fixed. Also added [help for Ishmael detectors](https://www.pamguard.org/olhelp/detectors/ishmael/docs/ishmael_overview.html).

[Issue 249](https://github.com/PAMGuard/PAMGuard/issues/249): Error in LTSA dialog. This was only causing the dialog to fail to update to the correct data source, not affecting detection.

[Issue 248](https://github.com/PAMGuard/PAMGuard/issues/248): Mapping of hydrophones. Hopefully now fixed so that hydrophone mapping changes are used in bearing localisers.

[Issue 247](https://github.com/PAMGuard/PAMGuard/issues/247): Make correct interpretation of invalid speed and heading values (given as 102.3knots and 360.0 degrees in the data)

Fixed some dialogs in localiser that were not showing properly on macOS.

Updated to latest X3 library which fixes zero-pad bugs when processing SoundTrap data
