---
title: "Version 2.02.19"
description: "PAMGuard version 2.02.19 is now available for Windows and Mac"
date: 2026-08-11
---

[PAMGuard version 2.02.19](../downloadsurvey.qmd) is now available for Windows and Mac.

## PAMGuard 2.02.19 is now available

Version [2.02.19](../downloadsurvey.qmd) includes a number of minor new features and bug fixes. 

We've started to distribute an installer for Debian-based Linux systems - we are trialling to see how this goes. Linux is still a very fragmented ecosystem, and we can't guarantee that the installer will work on all Debian-based Linux distributions (it won't work on Fedora, etc.), but we hope it will make installation easier for some users. There are also some instructions [here](https://github.com/PAMGuard/PAMGuard/blob/main/build/COMPILE.md) on how to manually build PAMGuard on Linux. 

We also implemented Apple's new security features, so the macOS installer should now only warn users once that PAMGuard was downloaded from the Internet, and the app should be able to access the computer's microphone (subject to user permission) without any workarounds. Get in touch if this does not work.

::: callout-note
We know it's frustrating if PAMGuard does not work, and (subject to [funding](../funding.qmd)) we are taking steps to make releases more stable by developing a new test framework. It's going to take time, and we won't catch every bug, but it should mean that in the coming few years PAMGuard is generally more resilient to bugs, making life easier for developers and users!
:::

Here's a full list of what was done and you can always check out [GitHub Issues page](https://github.com/PAMGuard/PAMGuard/issues) to see what specifically was fixed.

## New Features

GeoTIFF Map Layer. Can now use a geo referenced image File as a base layer on the PAMGuard Map. These can be created using many suitable GIS packages. See Help for details.

Version Logging. PAMGuard version information and versions of all loaded plugin modules is written to the database table Version\_Information every time PAMGuard starts.

Automatic NMEA serial port selection. New option, which will try available serial ports in turn until one is found that s returning NMEA data.

[Issue 311](https://github.com/PAMGuard/PAMGuard/issues/311): Improved bearing errors from beam former bearing calculator and fix of error estimation in the crossed bearing localiser. Updates to the underlying math and display graphics.

[Issue 323](https://github.com/PAMGuard/PAMGuard/issues/323): Do a database commit whenever the File menu is used to view the database.

[Issue 324](https://github.com/PAMGuard/PAMGuard/issues/324): Database and binary stores automatically open configuration dialogs when added to a new configuration. 

[Issue 325](https://github.com/PAMGuard/PAMGuard/issues/325): Improved NMEA input resetting, e.g. if USB GPS becomes temporarily unplugged. Also updated code to support additional NMEA sources through the plugin system for 3rd party developers.

## Bug Fixes

[Issue 292](https://github.com/PAMGuard/PAMGuard/issues/296): Stop printing unnecessary wav file format warnings when they do no harm.

[Issue 300](https://github.com/PAMGuard/PAMGuard/issues/300): Null pointer returned by the Ishmael Spectrogram Correlation detector. Fixed.

[Issue 302](https://github.com/PAMGuard/PAMGuard/issues/302): Whistle export errors when using multiple whistle and moan detectors

[Issue 306](https://github.com/PAMGuard/PAMGuard/issues/306): Tethys export. Options to limit number of items per Detections document to about 100k.

[Issue 307](https://github.com/PAMGuard/PAMGuard/issues/307): Tethys not exporting correct count of data points in Detections documents.

[Issues 308](https://github.com/PAMGuard/PAMGuard/issues/308) and [310](https://github.com/PAMGuard/PAMGuard/issues/310): 3D Localiser / crossed bearing localiser now correctly showing and saving settings

[Issue 315](https://github.com/PAMGuard/PAMGuard/issues/315): AIS Memory leak fixed. Only occurred when a vessel was in range indefinitely, e.g. in port.

[Issue 317](https://github.com/PAMGuard/PAMGuard/pull/317), [318](https://github.com/PAMGuard/PAMGuard/pull/318), and [319](https://github.com/PAMGuard/PAMGuard/pull/319): Small fixes to improve file cataloguing and error management when running headless on a server.

[Issue 322](https://github.com/PAMGuard/PAMGuard/issues/322): Logger forms error if counter information is read when form output tables don t exist.

[Issue 327](https://github.com/PAMGuard/PAMGuard/pull/327): Fix to Ishmeal spectrogram correlation application of changed settings.

[Issue 328](https://github.com/PAMGuard/PAMGuard/issues/328): Fix to Ishmeal spectrogram correlation dialog.

[Issue 329](https://github.com/PAMGuard/PAMGuard/pull/329): Fix to spectrogram noise process so that not all processes have to be run together.
