---
title: "PAMGuard Tutorials"
listing: 
  - id: tutorial_listing
    type: grid
    field-display-names:
      pres: "Prerequisites"
    categories: true
    fields: [image, title, description]
    sort: dispord
    exclude:
      fileusage: notlisted
#    contents: 
#      - "tutorials/*.qmd"
      
#  - id: as_table
#    type: table
#    field-display-names:
#      pres: "Prerequisites"
#      shortdesc: "Description"
#      Title: "Tutorial"
#    fields: [title, pres, shortdesc, image]
#    image-height: 80px
#    sort: dispord
#    contents: 
#      - "tutorials/*.qmd"
---

::: {#boldcentred}
The [ECS Conference](https://www.europeancetaceansociety.eu/conference-2026) is coming to Scotland. We'll be organising a one day PAMGuard training workshop on either Monday 20th, or Tuesday 221st April. Watch this space, and keep an eye on the [conference website](https://www.europeancetaceansociety.eu/conference-2026) for updates.
:::

PAMGuard Tutorials are an excellent way to familiarise yourself with PAMGuard. If you're new to PAMGuard, you should start with one of the introductory tutorials, [Getting Started](./tutorials/getstarted.qmd), or [Introduction to PAMGuard](./tutorials/staticmonitoring.qmd) before trying the more advanced ones.

The tutorials all use freely available pre-recorded sound files and will run on any [compatible computer](systemreq.qmd) without the need for specialist equipment.

::: {#tutorial_listing}
:::

Subject to [funding](funding.qmd), we're currently trying to expand these to cover more areas of what PAMGuard can do.
