---
title: "Funding"
format: html
include-in-header:
  - head-includes.html
css: styles.css
---

Initial funding for the PAMGuard project came from the International Association of Geophysical Contractors [Sound and Marine Life Joint Industry Programme](https://www.soundandmarinelife.org/)

Funding for more recent developments has come from a wide variety of sources including governments, other research organisations, offshore renewable energy companies, and NGO's.

Many developments such as the [Tritech multibeam sonar module](./plugins/tritech.qmd), and the latest [ROCCA Classifiers](./rocca/rocca.qmd), occur because we need those developments to fulfill our own research goals.

While these mechanisms fund some of the developments, they do not pay for time we spend on user support, dealing with bugs, managing new releases and updating this website.

In 2016 we set up a system of [voluntary contributions](voluntary.qmd), whereby users within the offshore industry (oil and gas, renewables) would pay a contribution to PAMGuard of US\$5 per day.

We are now setting up a much simpler system whereby companies can easily [donate to PAMGuard](https://www.st-andrews.ac.uk/development/pamguard/) through the Universities Science and Medicine donation form (please ensure you select PAMGuard from the list of funding designations!).

<center><a href="https://www.st-andrews.ac.uk/development/pamguard/" class="btn btn-primary btn-sm" role="button" data-toggle="tooltip" title="Help support PAMGuard with a charitable donation" 
        style="background: radial-gradient(circle, #3a99ffff, #2B4E80 ); /* Gradient from blue to purple */
        border: none;
        color: white;
        padding: 15px 32px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 18px;
        font-weight: bold;
        border-radius: 12px;
        width: 300px; /* Set a fixed width */" 
        target="donate"> <i class="fas fa-donate" style="margin-right: 8px;"></i>Donate to PAMGuard</a></center>

### How we'll spend the money

Subject to having enough funds to employ a new programmer / assistant, there are several important areas of PAMGuard that we want to work on. Tasks can broadly be split into maintenance tasks and new functionality.

#### Maintenance Tasks

Without code maintenance, there is a risk that PAMGuard will become unstable or inefficient on new computer hardware and new versions of operating systems. Mac have already switched to ARM processors, and Windows are heading in the same direction. Generally, this is a good thing since these processors are ore powerful, and many are now optimised for running deep learning (AI) models. However, it's also the case that to get the most out of these processors, we're going to have to rebuild parts of PAMGuard and make different installers. All of this takes time and resource.

We aim to:

1.  Continue user support
2.  Improve pre-release testing
3.  Update user tutorials
4.  Build new Installers for Windows ARM Processors
5.  Provide better support for Mac computers, including real time processing
6.  Further update this website

#### New Functionality

The marine mammal acoustics community have become increasingly active during the lifetime of PAMGuard, particularly through the [DCLDE workshops](https://dclde2024.com/previous/) which are generally held every two years. Several of the new algorithms that have been presented at these workshops would be suitable for implementation into PAMGuard. However, taking Matlab or Python code that was written to process files offline can require a lot of work to get it running in real time.

In particular, we want to:

1.  Continue to integrate Machine Learning algorithms / AI throughout PAMGuard.
2.  Implement newly developed methods for whistle extraction into PAMGuards real time framework.
3.  Develop and implement better click train detection / tracking algorithms.
