---
title: "Plugin PAMGuard Modules"
listing: 
  type: grid
  contents: 
    - "plugins/*.qmd"
---

Read [here](coremodules.html) for information about PAMGuard's modular architecture.

Most of the modules, that most users will ever want to use, are included in the [core modules](coremodules.html) which are built into PAMGuard and are available in all installations.

As well as the core modules, there are also **plugin modules** that you can add to an existing PAMGuard installation. Once added, they behave the same way as the core modules.

Sometimes, modules are developed as plugins, and if they are useful and likely to benefit many users, we'll add them to the core.

There are several reasons why people may want to create or use plugin modules:

1.  Developers can make a module and distribute it to users without having to get approval in any form from the PAMGuard team.
2.  By distributing the module themselves, it's easier for them to get credit for their work where credit is due.
3.  The module may be experimental, untested, and certainly doesn't have any help, so we don't particularly want it in the main release since it won't make users happy.
4.  The module may have such niche functionality that no one will want to use it and it just clutters the PAMGuard menus.
5.  All of the above

### Installation

Usually, a plugin is distributed in the form of a .jar file (that's compiled Java, the language PAMGuard is written in). All you have to do is copy the file into the plugins folder in the PAMGuard installation directory (e.g. C:\\Program Files\\Pamguard\\plugins for most installation). In some cases, you may need to add other files, for example some additional C libraries. In this case check any instructions distributed with the plugin.

### Available Plugin Modules

These are modules developed by the PAMGuard team, or hosted on our website. Other developers may distribute plugins from their own sites.
